CascadedPolygonUnion: Remove unused code
Duplicated with include/geos/geom/BinaryOp.h and unused:

CascadedPolygonUnion.cpp:51:1: error: unused function 'check_valid' [-Werror,-Wunused-function]
check_valid(const geos::geom::Geometry& g, const std::string& label, bool doThrow = false, bool validOnly = false)
1 error generated.