geos: add missing <cstdint> includes for gcc-13
Without the change build on `gcc-13` fails as:

    geos/include/geos/geomgraph/TopologyLocation.h:143:52: error: 'uint32_t' has not been declared
      143 |     bool isEqualOnSide(const TopologyLocation& le, uint32_t locIndex) const
          |                                                    ^~~~~~~~