~MCIndexSegmentSetMutualIntersector: Remove unused variables
MCIndexSegmentSetMutualIntersector.cpp:107:26: error: unused variable 'i' [-Werror,-Wunused-variable]
    MonoChains::iterator i, e;
                         ^
MCIndexSegmentSetMutualIntersector.cpp:107:29: error: unused variable 'e' [-Werror,-Wunused-variable]
    MonoChains::iterator i, e;
                            ^
2 errors generated